# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 03:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='from date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='to date')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['from_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='http://localhost:9200')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('filedir', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FSCrawlerJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='', max_length=255)),
                ('job_dir', models.CharField(default='//dsto/nsid/Task_data/Common/Resources/Conferences', max_length=500)),
                ('job_settings_file', models.FilePathField(default='C:\\Users\\Dillon Davies\\.fscrawler\\')),
                ('job_run', models.BooleanField(default=False)),
                ('job_conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Conference')),
            ],
            options={
                'ordering': ['job_name'],
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Index'),
        ),
    ]
